
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbshmfktbafznerkgune.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhic2htZmt0YmFmem5lcmtndW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Njk2NTYsImV4cCI6MjA2MzA0NTY1Nn0.ilnL-uSW_lSOyyjoAWlLXEMDhIDmp3LPeEhuuwJyxOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
